### ISSUE TITLE
'RichEditDocumentServer' is a namespace but is used like a type.

### ISSUE THREAD

**Issue by ayangh** [DevExpress-Examples/word-processing-document-api-examples-t418535#10]
Error	CS0118	'RichEditDocumentServer' is a namespace but is used like a type	RichEditDocumentServerAPIExample.

Error has gone when "static void InsertRichTextInTextBox(RichEditDocumentServer wordProcessor)" is chnaged to "static void InsertRichTextInTextBox(IRichEditDocumentServer wordProcessor)"

**Comment by ayangh** [comment]
Problem solved by changing "RichEditDocumentServer" to "DevExpress.XtraRichEdit.RichEditDocumentServer".

Though I've add the reference;
using DevExpress.XtraRichEdit;

**Comment by geumjaLee** [comment]
Sorry, but I couldn't reproduce the issue.
