### ISSUE TITLE
'Shape' does not contain a definition for 'ShapeFormat' 

### ISSUE THREAD

**Issue by ayangh** [DevExpress-Examples/word-processing-document-api-examples-t418535#9]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'Shape' does not contain a definition for 'ShapeFormat' and no accessible extension method 'ShapeFormat' accepting a first argument of type 'Shape' could be found (are you missing a using directive or an assembly reference?)

Though I've correctly imported DevExpress.XtraRichEdit.API.Native and I'm using the version DevExpress 19.1

**Comment by geumjaLee** [comment]
This member was added in v20.1. Please, check the branch with an earlier version (18.2.2+)
